# fly.toml app configuration file generated for web-chatting-socket on 2025-11-18T11:01:42+07:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'web-chatting-socket'
primary_region = 'sjc'

[build]
  dockerfile = 'Dockerfile.socket'

[env]
  NODE_ENV = 'production'
  PORT = '8080'

[processes]
  app = 'node socket-server.js'

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = false
  auto_start_machines = true
  min_machines_running = 1
  processes = ['app']

[[vm]]
  size = 'shared-cpu-1x'
  memory = '256mb'
